# Generated by Django 4.0.5 on 2022-07-15 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comprar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='comprar',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
