# Generated by Django 4.0.5 on 2022-07-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_delete_cliente_delete_comprar_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comprar',
            fields=[
                ('Producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('Cantidad', models.CharField(max_length=100, verbose_name='Cantidad')),
                ('Tipotarjeta', models.CharField(max_length=100, verbose_name='Tipotarjeta')),
                ('Numerotarjeta', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Numerotarjeta')),
                ('Fecha_expira', models.CharField(max_length=100, verbose_name='Fecha_expira')),
                ('Cvv', models.CharField(max_length=100, verbose_name='CVV')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ids', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('asunto', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=20)),
            ],
        ),
    ]
